In [4]:
import pandas as pd

In [5]:
df = pd.read_excel('Canada.xlsx', skiprows=range(20), sheet_name='Canada by Citizenship', skipfooter=2)
df.head()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1

In [6]:
df.tail()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
190,Immigrants,Foreigners,Viet Nam,935,Asia,920,South-Eastern Asia,902,Developing regions,1191,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
191,Immigrants,Foreigners,Western Sahara,903,Africa,912,Northern Africa,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
192,Immigrants,Foreigners,Yemen,935,Asia,922,Western Asia,902,Developing regions,1,...,124,161,140,122,133,128,211,160,174,217
193,Immigrants,Foreigners,Zambia,903,Africa,910,Eastern Africa,902,Developing regions,11,...,56,91,77,71,64,60,102,69,46,59
194,Immigrants,Foreigners,Zimbabwe,903,Africa,910,Eastern Africa,902,Developing regions,72,...,1450,615,454,663,611,508,494,434,437,407

In [7]:
df.size

8385

In [8]:
df.shape

(195, 43)

In [9]:
df.dtypes

Type        object
Coverage    object
OdName      object
AREA         int64
AreaName    object
REG          int64
RegName     object
DEV          int64
DevName     object
1980         int64
1981         int64
1982         int64
1983         int64
1984         int64
1985         int64
1986         int64
1987         int64
1988         int64
1989         int64
1990         int64
1991         int64
1992         int64
1993         int64
1994         int64
1995         int64
1996         int64
1997         int64
1998         int64
1999         int64
2000         int64
2001         int64
2002         int64
2003         int64
2004         int64
2005         int64
2006         int64
2007         int64
2008         int64
2009         int64
2010         int64
2011         int64
2012         int64
2013         int64
dtype: object

In [10]:
df.columns

Index([    'Type', 'Coverage',   'OdName',     'AREA', 'AreaName',      'REG',
        'RegName',      'DEV',  'DevName',       1980,       1981,       1982,
             1983,       1984,       1985,       1986,       1987,       1988,
             1989,       1990,       1991,       1992,       1993,       1994,
             1995,       1996,       1997,       1998,       1999,       2000,
             2001,       2002,       2003,       2004,       2005,       2006,
             2007,       2008,       2009,       2010,       2011,       2012,
             2013],
      dtype='object')

In [11]:
df.drop(columns=['Type', 'Coverage', 'AREA', 'REG', 'DEV'], inplace=True)

In [12]:
df.head()

,OdName,AreaName,RegName,DevName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,1,1

In [13]:
df.rename(columns= { 'OdName' : 'Country', 'AreaName' : 'Continent' }, inplace=True)

In [14]:
df.head()

,Country,Continent,RegName,DevName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,1,1

In [15]:
df.Country

0         Afghanistan
1             Albania
2             Algeria
3      American Samoa
4             Andorra
            ...
190          Viet Nam
191    Western Sahara
192             Yemen
193            Zambia
194          Zimbabwe
Name: Country, Length: 195, dtype: object

In [16]:
df.Country.values

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bhutan', 'Bolivia (Plurinational State of)',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China',
       'China, Hong Kong Special Administrative Region',
       'China, Macao Special Administrative Region', 'Colombia',
       'Comoros', 'Congo', 'Costa Rica', "CÃ´te d'Ivoire", 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic",
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan',
       'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Qatar', 'Republic of Korea',
       'Republic of Moldova', 'Romania', 'Russian Federation', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
       'State of Palestine', 'Sudan', 'Suriname', 'Swaziland', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Thailand',
       'The former Yugoslav Republic of Macedonia', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Western Sahara',
       'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [17]:
df[ ['Country', 'Continent', 'DevName', 2010, 2013] ]

            Country Continent             DevName  2010  2013
0       Afghanistan      Asia  Developing regions  1758  2004
1           Albania    Europe   Developed regions   561   603
2           Algeria    Africa  Developing regions  4752  4331
3    American Samoa   Oceania  Developing regions     0     0
4           Andorra    Europe   Developed regions     0     1
..              ...       ...                 ...   ...   ...
190        Viet Nam      Asia  Developing regions  1942  2112
191  Western Sahara    Africa  Developing regions     0     0
192           Yemen      Asia  Developing regions   211   217
193          Zambia    Africa  Developing regions   102    59
194        Zimbabwe    Africa  Developing regions   494   407

[195 rows x 5 columns]

In [19]:
df.DevName.unique()

array(['Developing regions', 'Developed regions'], dtype=object)

In [20]:
df.Continent.unique()

array(['Asia', 'Europe', 'Africa', 'Oceania',
       'Latin America and the Caribbean', 'Northern America'],
      dtype=object)

In [21]:
df[ df['Country'] == 'India' ]

,Country,Continent,RegName,DevName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
79,India,Asia,Southern Asia,Developing regions,8880,8670,8147,7338,5704,4211,...,28235,36210,33848,28742,28261,29456,34235,27509,30933,33087

In [22]:
df[ df['Country'] == 'India' ][2010]

79    34235
Name: 2010, dtype: int64

In [23]:
df[ df['Continent'] == 'Asia' ]

,Country,Continent,RegName,DevName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
8,Armenia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,147,224,218,198,205,267,252,236,258,207
11,Azerbaijan,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,230,359,236,203,125,165,209,138,161,57
13,Bahrain,Asia,Western Asia,Developing regions,0,2,1,1,1,3,...,12,12,12,22,9,35,28,21,39,32
14,Bangladesh,Asia,Southern Asia,Developing regions,83,84,86,81,98,92,...,2660,4171,4014,2897,2939,2104,4721,2694,2640,3789
20,Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,...,1,5,10,7,36,865,1464,1879,1075,487
25,Brunei Darussalam,Asia,South-Eastern Asia,Developing regions,79,6,8,2,2,4,...,3,4,5,11,10,5,12,6,3,6
30,Cambodia,Asia,South-Eastern Asia,Developing regions,12,19,26,33,10,7,...,348,370,529,460,354,203,200,196,233,288
36,China,Asia,Eastern Asia,Developing regions,5123,6682,3308,1863,1527,1816,...,36619,42584,33518,27642,30037,29622,30391,28502,33024,34129
37,"China, Hong Kong Special Administrative Region",Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,...,536,729,712,674,897,657,623,591,728,774
38,"China, Macao Special Administrative Region",Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,...,21,21,32,16,12,21,21,13,33,29
46,Cyprus,Asia,Western Asia,Developing regions,132,128,84,46,46,43,...,11,7,9,4,7,6,18,6,12,16
48,Democratic People's Republic of Korea,Asia,Eastern Asia,Developing regions,1,1,3,1,4,3,...,15,14,10,7,19,11,45,97,66,17
66,Georgia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,106,114,125,132,112,128,126,139,147,125
79,India,Asia,Southern Asia,Developing regions,8880,8670,8147,7338,5704,4211,...,28235,36210,33848,28742,28261,29456,34235,27509,30933,33087
80,Indonesia,Asia,South-Eastern Asia,Developing regions,186,178,252,115,123,100,...,552,632,613,657,661,504,712,390,395,387
81,Iran (Islamic Republic of),Asia,Southern Asia,Developing regions,1172,1429,1822,1592,1977,1648,...,6348,5837,7480,6974,6475,6580,7477,7479,7534,11291
82,Iraq,Asia,Western Asia,Developing regions,262,245,260,380,428,231,...,1796,2226,1788,2406,3543,5450,5941,6196,4041,4918
84,Israel,Asia,Western Asia,Developing regions,1403,1711,1334,541,446,680,...,2788,2446,2625,2401,2562,2316,2755,1970,2134,1945
87,Japan,Asia,Eastern Asia,Developed regions,701,756,598,309,246,198,...,973,1067,1212,1250,1284,1194,1168,1265,1214,982
88,Jordan,Asia,Western Asia,Developing regions,177,160,155,113,102,179,...,1733,1940,1827,1421,1581,1235,1831,1635,1206,1255
89,Kazakhstan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,545,506,408,436,394,431,377,381,462,348
92,Kuwait,Asia,Western Asia,Developing regions,1,0,8,2,1,4,...,74,66,35,62,53,68,67,58,73,48
93,Kyrgyzstan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,245,173,161,135,168,173,157,159,278,123
94,Lao People's Democratic Republic,Asia,South-Eastern Asia,Developing regions,11,6,16,16,7,17,...,38,42,74,53,32,39,54,22,25,15
96,Lebanon,Asia,Western Asia,Developing regions,1409,1119,1159,789,1253,1683,...,3293,3709,3802,3467,3566,3077,3432,3072,1614,2172
105,Malaysia,Asia,South-Eastern Asia,Developing regions,786,816,813,448,384,374,...,401,593,580,600,658,640,802,409,358,204
106,Maldives,Asia,Southern Asia,Developing regions,0,0,0,1,0,0,...,1,0,0,2,1,7,4,3,1,1
114,Mongolia,Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,...,34,59,64,82,59,118,169,103,68,99
118,Myanmar,Asia,South-Eastern Asia,Developing regions,80,62,46,31,41,23,...,191,210,953,1887,975,1153,556,368,193,262
121,Nepal,Asia,Southern Asia,Developing regions,1,1,6,1,2,4,...,404,607,540,511,581,561,1392,1129,1185,1308
129,Oman,Asia,Western Asia,Developing regions,0,0,0,8,0,0,...,12,14,18,16,10,7,14,10,13,11
130,Pakistan,Asia,Southern Asia,Developing regions,978,972,1201,900,668,514,...,13399,14314,13127,10124,8994,7217,6811,7468,11227,12603
136,Philippines,Asia,South-Eastern Asia,Developing regions,6051,5921,5249,4562,3801,3150,...,14004,18139,18400,19837,24887,28573,38617,36765,34315,29544
139,Qatar,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,5,11,2,5,9,6,18,3,14,6
140,Republic of Korea,Asia,Eastern Asia,Developing regions,1011,1456,1572,1081,847,962,...,5352,5832,6215,5920,7294,5874,5537,4588,5316,4509
151,Saudi Arabia,Asia,Western Asia,Developing regions,0,0,1,4,1,2,...,128,198,252,188,249,246,330,278,286,267
156,Singapore,Asia,South-Eastern Asia,Developing regions,241,301,337,169,128,139,...,311,392,298,690,734,366,805,219,146,141
162,Sri Lanka,Asia,Southern Asia,Developing regions,185,371,290,197,1086,845,...,4495,4930,4714,4123,4756,4547,4422,3309,3338,2394
163,State of Palestine,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,376,453,627,441,481,400,654,555,533,462
169,Syrian Arab Republic,Asia,Western Asia,Developing regions,315,419,409,269,264,385,...,1116,1458,1145,1056,919,917,1039,1005,650,1009
170,Tajikistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,14,85,46,44,15,50,52,47,34,39
171,Thailand,Asia,South-Eastern Asia,Developing regions,56,53,113,65,82,66,...,392,575,500,487,519,512,499,396,296,400
177,Turkey,Asia,Western Asia,Developing regions,481,874,706,280,338,202,...,1736,2065,1638,1463,1122,1238,1492,1257,1068,729
178,Turkmenistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,16,40,26,37,13,20,30,20,20,14
182,United Arab Emirates,Asia,Western Asia,Developing regions,0,2,2,1,2,0,...,41,31,42,37,33,37,86,60,54,46
187,Uzbekistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,175,330,262,284,215,288,289,162,235,167
190,Viet Nam,Asia,South-Eastern Asia,Developing regions,1191,1829,2162,3404,7583,5907,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
192,Yemen,Asia,Western Asia,Developing regions,1,2,1,6,0,18,...,124,161,140,122,133,128,211,160,174,217

In [24]:
df[ df['DevName'] == 'Developed regions' ]

,Country,Continent,RegName,DevName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,1,1
9,Australia,Oceania,Australia and New Zealand,Developed regions,702,639,484,317,317,319,...,930,909,875,1033,1018,1018,933,851,982,1121
10,Austria,Europe,Western Europe,Developed regions,234,238,201,117,127,165,...,118,122,102,98,91,109,124,84,102,90
16,Belarus,Europe,Eastern Europe,Developed regions,0,0,0,0,0,0,...,543,558,439,568,524,454,438,357,277,247
17,Belgium,Europe,Western Europe,Developed regions,511,540,519,297,183,181,...,411,400,302,363,335,358,363,332,402,379
22,Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,188,211,217,209,182,156,168,140,121,119
26,Bulgaria,Europe,Eastern Europe,Developed regions,24,20,12,33,11,24,...,2022,1738,1419,1172,994,784,556,365,451,512
32,Canada,Northern America,Northern America,Developed regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,2
44,Croatia,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,151,128,102,102,131,92,91,135,112,125
47,Czech Republic,Europe,Eastern Europe,Developed regions,0,0,0,0,0,0,...,191,193,146,137,104,159,168,128,173,174
50,Denmark,Europe,Northern Europe,Developed regions,272,293,299,106,93,73,...,89,62,101,97,108,81,92,93,94,81
59,Estonia,Europe,Northern Europe,Developed regions,0,0,0,0,0,0,...,27,26,18,34,34,26,28,15,26,45
62,Finland,Europe,Northern Europe,Developed regions,208,205,170,70,83,69,...,54,67,51,62,89,63,63,72,62,76
63,France,Europe,Western Europe,Developed regions,1729,2027,2219,1490,1169,1177,...,4391,4429,4002,4290,4532,5051,4646,4080,6280,5623
67,Germany,Europe,Western Europe,Developed regions,1626,1977,3062,2376,1610,1441,...,2020,2226,2767,2449,3833,3887,2956,2053,1702,1217
69,Greece,Europe,Southern Europe,Developed regions,1065,953,897,633,580,584,...,120,100,74,110,107,119,101,102,146,298
77,Hungary,Europe,Eastern Europe,Developed regions,205,310,397,337,310,522,...,671,516,520,425,383,312,354,287,300,425
78,Iceland,Europe,Northern Europe,Developed regions,17,33,10,9,13,6,...,23,10,2,15,13,15,30,38,42,72
83,Ireland,Europe,Northern Europe,Developed regions,781,895,707,298,327,287,...,244,224,283,300,412,395,547,525,725,1015
85,Italy,Europe,Southern Europe,Developed regions,1820,2057,1480,820,858,667,...,334,344,325,320,370,429,434,374,440,545
87,Japan,Asia,Eastern Asia,Developed regions,701,756,598,309,246,198,...,973,1067,1212,1250,1284,1194,1168,1265,1214,982
95,Latvia,Europe,Northern Europe,Developed regions,0,0,0,0,0,0,...,94,77,69,88,67,85,70,103,202,213
100,Liechtenstein,Europe,Western Europe,Developed regions,1,4,2,0,0,3,...,0,1,0,0,1,1,0,2,1,0
101,Lithuania,Europe,Northern Europe,Developed regions,1,1,0,0,0,1,...,220,167,113,108,109,63,57,52,77,145
102,Luxembourg,Europe,Western Europe,Developed regions,14,4,2,5,1,3,...,9,10,9,9,3,5,8,11,6,7
108,Malta,Europe,Southern Europe,Developed regions,191,242,153,64,60,68,...,28,28,24,7,21,18,17,8,9,4
113,Monaco,Europe,Western Europe,Developed regions,0,0,0,0,0,1,...,1,1,1,1,0,0,4,1,3,1
115,Montenegro,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,0,0,7,19,10,14,19,26,9
122,Netherlands,Europe,Western Europe,Developed regions,1889,1858,1852,716,560,510,...,749,813,837,615,818,786,759,586,504,395
124,New Zealand,Oceania,Australia and New Zealand,Developed regions,602,480,364,140,164,148,...,350,370,318,350,480,520,490,375,417,415
128,Norway,Europe,Northern Europe,Developed regions,116,77,106,51,31,54,...,73,57,53,73,66,75,46,49,53,59
137,Poland,Europe,Eastern Europe,Developed regions,863,2930,5881,4546,3588,2819,...,1533,1405,1263,1235,1267,1013,795,720,779,852
138,Portugal,Europe,Southern Europe,Developed regions,4473,3486,2432,1433,1398,1451,...,336,338,424,405,665,623,629,528,560,630
141,Republic of Moldova,Europe,Eastern Europe,Developed regions,0,0,0,0,0,0,...,628,655,803,1099,1127,1535,1988,1367,1416,1231
142,Romania,Europe,Eastern Europe,Developed regions,375,438,583,543,524,604,...,5755,5048,4468,3834,2837,2076,1922,1776,1588,1512
143,Russian Federation,Europe,Eastern Europe,Developed regions,0,0,0,0,0,0,...,3989,3972,3117,2983,2690,2931,2288,1963,2079,2466
149,San Marino,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
153,Serbia,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,0,3,50,259,365,271,299,395,297
157,Slovakia,Europe,Eastern Europe,Developed regions,0,0,0,0,0,0,...,597,369,241,215,125,128,135,134,136,105
158,Slovenia,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,17,23,11,29,18,27,12,13,36,20
161,Spain,Europe,Southern Europe,Developed regions,211,299,260,133,137,98,...,133,126,124,137,169,195,174,179,262,331
167,Sweden,Europe,Northern Europe,Developed regions,281,308,222,176,128,158,...,129,205,139,193,165,167,159,134,140,140
168,Switzerland,Europe,Western Europe,Developed regions,806,811,634,370,326,314,...,337,270,258,308,357,328,285,266,243,201
172,The former Yugoslav Republic of Macedonia,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,443,285,256,211,191,198,188,130,126,112
181,Ukraine,Europe,Eastern Europe,Developed regions,0,0,0,0,0,0,...,2431,2270,1973,2218,1937,2367,3159,2515,2265,2487
183,United Kingdom of Great Britain and Northern I...,Europe,Northern Europe,Developed regions,22045,24796,20620,10015,10170,9564,...,7533,7258,7140,8216,8979,8876,8724,6204,6195,5827
185,United States of America,Northern America,Northern America,Developed regions,9378,10030,9074,7100,6661,6543,...,6990,8394,9613,9463,10190,8995,8142,7676,7891,8501